<a href="https://colab.research.google.com/github/yunssup/Python-Pandas-300-for-Beginners-in-Data-Analysis/blob/main/%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_%EC%9E%85%EB%AC%B8%EC%9E%90%EB%A5%BC_%EC%9C%84%ED%95%9C_%ED%8C%90%EB%8B%A4%EC%8A%A4_300_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## ***넘파이 001~010***

In [ ]:
import numpy as np

In [ ]:
# 리스트를 넘파이의 ndarray 객체로 변환해보세요.
data = [1, 2, 3]
np.array(data)

array([1, 2, 3])

In [ ]:
# 0부터 99까지의 정수가 저장된 ndarray 객체를 만들어 보세요.
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
#구구단 3단의 결과가 저장된 ndarray 객체를 만들어 보세요.
arr = np.arange(1,10)*3
arr

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
# 1000보다 작은 짝수가 저장된 ndarray 객체를 만들어 보세요.
# 3번째 파라미터는 증감폭을 의미
arr = np.arange (1,100,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
#0부터 1까지 0.1 간격으로 구성된 ndarray를 생성해보세요. 1은 포함되지 않습니다.
arr = np.arange (0,1,0.1)
arr

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
# 리스트에는 6개의 데이터가 저장돼 있습니다.

# data = [0, 1, 2, 3, 4, 5]

# 다음과 같이 2행 3열의 ndarray로 변환하세요.

# [[0 1 2]
#  [3 4 5]]

data = [0, 1, 2, 3, 4, 5]
arr = np.array(data)
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 다음의 2차원 ndarray 1차원 ndarray로 변환하세요.

arr = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

arr.reshape(6)
arr.flatten()

array([0, 1, 2, 3, 4, 5])

In [ ]:
# 주어진 ndarray를 다음과 같이 변경해 보세요.

# arr = np.arange(3)

arr.reshape(3,1)

array([[0],
       [1],
       [2]])

에러의 원인을 설명하세요.



```
> np.arange(6).reshape(2, 4)
ValueError: cannot reshape array of size 6 into shape (2,4)
```

6개의 데이터가 저장된 ndarray를 생성했는데 이를 2행 4열의 ndarray로 변환하니 데이터의 개수가 부족함. 따라서 에러가 발생.


## ***넘파이 011~020***

In [ ]:
#다음과 같이 2차원 ndarray 객체를 정의하세요.

data = [
    [0, 1, 2],
    [3, 4, 5]
]
arr = np.array(data)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 0~5 까지 일차원 배열 생성한 뒤 shape 를 변경하면 코드가 간단해짐
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# 1이 20개 저장된 아래의 ndarray 객체를 만들어 보세요.
np.ones(20, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:

np.ones(20, dtype=int).reshape(4, 5)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
np.ones(100, dtype=int).reshape(10, 10)
arr = arr*255
arr

array([65025, 65025, 65025, 65025, 65025, 65025, 65025, 65025, 65025,
       65025, 65025, 65025, 65025, 65025, 65025, 65025, 65025, 65025,
       65025, 65025])

In [ ]:
# 3x4 (행x열) 크기의 0으로 채워진 배열을 생생해보세요.
arr = np.zeros((3, 4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# [1, 2, 3]을 np.int32 타입의 ndarray 배열로 생성하세요.

import numpy as np

data = [1, 2, 3]
arr = np.ndarray(data, dtype=np.int32)
arr

array([[[823900570,     23560,         0],
        [        0,        64,         0]]], dtype=int32)

In [ ]:
#다음 배열의 데이터 타입을 확인해보세요.

arr = np.array([1, 2, 3])
arr.dtype

dtype('int64')

In [ ]:
arr = np.array(['1', '2', '3'])
arr.dtype
# 1 바이트 문자열

dtype('<U1')

In [ ]:
# 다음 데이터를 np.int16 타입의 배열로 형변환하세요.

arr = np.array([1, 2, 3])
arr.astype(np.int16)

array([1, 2, 3], dtype=int16)